global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: arbiscanner-web
    static_configs:
      - targets: ["web:8080"]
    metrics_path: /metrics

  - job_name: arbiscanner-admin
    static_configs:
      - targets: ["admin-api:8080"]
    metrics_path: /metrics

  - job_name: arbiscanner-telegram-notifier
    static_configs:
      - targets: ["telegram-notifier:8085"]
    metrics_path: /metrics

  - job_name: arbiscanner-arbitrage-scanner
    static_configs:
      - targets: ["arbitrage-scanner:8085"]
    metrics_path: /metrics
